# Generated by Django 5.2.8 on 2025-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], default='macho', max_length=10, verbose_name='Sexo'),
        ),
    ]
