# Generated by Django 5.2.8 on 2025-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_pet_raca_porte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do Bichinho"),
        ),
        migrations.AlterField(
            model_name="petimagem",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="pets/", verbose_name="Imagem"
            ),
        ),
    ]
